In [1]:
import pandas as pd

In [2]:
movie  = pd.read_csv('IMDB dataset.csv')

In [3]:
movie['review'][0]

"One of the other reviewers has mentioned that after watching just 1 Oz episode you'll be hooked. They are right, as this is exactly what happened with me.<br /><br />The first thing that struck me about Oz was its brutality and unflinching scenes of violence, which set in right from the word GO. Trust me, this is not a show for the faint hearted or timid. This show pulls no punches with regards to drugs, sex or violence. Its is hardcore, in the classic use of the word.<br /><br />It is called OZ as that is the nickname given to the Oswald Maximum Security State Penitentary. It focuses mainly on Emerald City, an experimental section of the prison where all the cells have glass fronts and face inwards, so privacy is not high on the agenda. Em City is home to many..Aryans, Muslims, gangstas, Latinos, Christians, Italians, Irish and more....so scuffles, death stares, dodgy dealings and shady agreements are never far away.<br /><br />I would say the main appeal of the show is due to the fa

In [5]:
movie.shape

(50000, 2)

In [14]:
d = pd.DataFrame({'col': ['People love AI', 'AI loves AIml' , 'People loves AIml']})

In [11]:
from sklearn.feature_extraction.text import CountVectorizer

In [12]:
cv = CountVectorizer()

In [18]:
d['col']

0       People love AI
1        AI loves AIml
2    People loves AIml
Name: col, dtype: object

In [16]:
cv.fit_transform(d['col']).toarray()

array([[1, 0, 1, 0, 1],
       [1, 1, 0, 1, 0],
       [0, 1, 0, 1, 1]])

In [17]:
cv.vocabulary_

{'people': 4, 'love': 2, 'ai': 0, 'loves': 3, 'aiml': 1}

In [19]:
cv = CountVectorizer(ngram_range=(2,2))

In [20]:
cv.fit_transform(d['col']).toarray()

array([[0, 1, 0, 1, 0],
       [1, 0, 1, 0, 0],
       [0, 0, 1, 0, 1]])

In [21]:
cv.vocabulary_

{'people love': 3,
 'love ai': 1,
 'ai loves': 0,
 'loves aiml': 2,
 'people loves': 4}

In [23]:
from sklearn.feature_extraction.text import TfidfVectorizer

In [24]:
tf = TfidfVectorizer

In [26]:
tf = TfidfVectorizer()
tf.fit_transform(d['col']).toarray()

array([[0.51785612, 0.        , 0.68091856, 0.        , 0.51785612],
       [0.57735027, 0.57735027, 0.        , 0.57735027, 0.        ],
       [0.        , 0.57735027, 0.        , 0.57735027, 0.57735027]])

In [27]:
tf.get_feature_names_out()

array(['ai', 'aiml', 'love', 'loves', 'people'], dtype=object)